guestbook:
  image: guestbook
  ports:
    - 3000:3000
  links:
    - redis-master:redis-master
    - redis-slave:redis-slave
redis-master:
  image: redis:3.0.7-alpine
  ports:
    - 6379:6379
redis-slave:
  image: gcr.io/google_samples/gb-redisslave:v1
  links:
    - redis-master:redis-master
  ports:
    - 3002:6379
