guestbook:
  image: guestbook
  ports:
    - 3000:3000
  links:
    - redismaster:redis-master
    - redisslave:redis-slave
redismaster:
  image: redis:3.0.7-alpine
  ports:
    - 6379:6379
redisslave:
  image: gcr.io/google_samples/gb-redisslave:v1
  links:
    - redismaster:redis-master
  ports:
    - 3002:6379
